# Generated by Django 5.2.5 on 2025-08-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "soundcloud_client_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "soundcloud_client_secret",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("soundcloud_user_id", models.IntegerField(blank=True, null=True)),
                (
                    "spotify_client_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "spotify_client_secret",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Credentials",
        ),
    ]
