# Generated by Django 5.2.5 on 2025-08-20 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_credential_delete_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="last_update_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 20, 8, 47, 23, 127999)
            ),
        ),
    ]
