# Generated by Django 5.2.5 on 2025-08-20 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_credential_last_update_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoundcloudAuthInformations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(blank=True, null=True)),
                ("token_type", models.CharField(blank=True, null=True)),
                ("expires_in", models.IntegerField()),
                ("expires_at", models.DateTimeField()),
                ("refresh_token", models.CharField(blank=True, null=True)),
                ("scope", models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="credential",
            name="last_update_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 20, 10, 41, 55, 960592, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
