# Generated by Django 5.2.5 on 2025-08-20 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_soundcloudauthinformations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="last_update_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 20, 11, 46, 15, 423536, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="soundcloudauthinformations",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="soundcloudauthinformations",
            name="expires_in",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
