# Generated by Django 5.2.5 on 2025-08-20 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_credential_last_update_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="last_update_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 20, 11, 48, 42, 846526, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
