# Generated by Django 5.2.5 on 2025-09-03 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_credential_last_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="last_update_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 3, 11, 55, 31, 436857, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
