# Generated by Django 5.2.5 on 2025-09-03 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_credential_last_update_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyAuthInformations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(blank=True, null=True)),
                ("token_type", models.CharField(blank=True, null=True)),
                ("expires_in", models.IntegerField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="credential",
            name="last_update_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 3, 12, 5, 19, 280343, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
