# Generated by Django 5.2.5 on 2025-09-03 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_spotifyauthinformations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="spotify_user_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="last_update_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 3, 12, 33, 40, 667398, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="soundcloudauthinformations",
            name="access_token",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="soundcloudauthinformations",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="soundcloudauthinformations",
            name="scope",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="soundcloudauthinformations",
            name="token_type",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="spotifyauthinformations",
            name="access_token",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="spotifyauthinformations",
            name="token_type",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
