# Generated by Django 5.2.5 on 2025-09-03 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_credential_spotify_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="last_update_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 3, 13, 26, 46, 613997, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
