# Generated by Django 5.2.5 on 2025-09-12 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_credential_last_update_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="last_update_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 12, 9, 45, 18, 949677, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="soundcloudauthinformations",
            name="access_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
